# General settings
server:
  port: 9000
spring:
  data:
    mongodb:
      host: 192.168.99.100
      port: 32768
      database: travelplan  
  
# Security  
security:
  oauth2:
    sso:
      loginPath: /index.html
    resource:
      tokenInfoUri: https://www.googleapis.com/oauth2/v2/tokeninfo
      userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo	
    client:
      id: google-oauth-client
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: authorization_code
      scope: https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/plus.login,https://www.googleapis.com/auth/plus.profile.emails.read
      useCurrentUri: false
      preEstablishedRedirectUri: http://localhost:9000/googleLogin
      authenticationScheme: query
      clientAuthenticationScheme: form