# General settings
server:
  port: 9000
spring:
  data:
    mongodb:
      host: 192.168.99.100
      port: 32768
      database: travelplan  
  
# Security
# https://spring.io/guides/tutorials/spring-boot-oauth2/  
security:
  oauth2:
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
      preferTokenInfo: false
    client:
      id: google-oauth-client
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: authorization_code
      #scope: https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/plus.login,https://www.googleapis.com/auth/plus.profile.emails.read
      scope:
        - profile
        - email
      useCurrentUri: false
      preEstablishedRedirectUri: http://localhost:9000/login
      authenticationScheme: query
      clientAuthenticationScheme: form